services:
  ollama:
    image: ghcr.io/amperecomputingai/ollama-ampere:0.0.4-ub22
    container_name: ollama-server
    volumes:
      - ollama:/root/.ollama
    network_mode: host
    environment:
      - "OLLAMA_HOST=0.0.0.0:11434"
    tty: true
    restart: unless-stopped

  open-webui:
    build:
      context: open-webui
      dockerfile: ../Dockerfile
      args:
        - "BASE_IMAGE=ghcr.io/amperecomputingai/release-aio-pytorch:1.11.1"
    image: ghcr.io/amperecomputingai/ampere-ai-llama-chat:0.0.4-rc
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    network_mode: host
    environment:
      - 'PORT=8080'
      - 'OLLAMA_BASE_URL=http://127.0.0.1:11434'
      - 'WEBUI_NAME=Ampere Llama Chat'
      - 'ENABLE_LITELLM=False'
      - 'WEBUI_AUTH=False'
      - 'GLOBAL_LOG_LEVEL=DEBUG'
    restart: unless-stopped

volumes:
  ollama:
    name: ollama-vol
  open-webui:
    name: open-webui-vol
