services:
  ollama:
    image: ghcr.io/amperecomputingai/ollama-ampere:0.0.1
    container_name: ollama-server
    volumes:
      - ollama:/root/.ollama
    network_mode: host
    tty: true
    restart: unless-stopped

  open-webui:
    image: ghcr.io/open-webui/open-webui:0.1.124
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    network_mode: host
    environment:
      - 'OLLAMA_BASE_URL=http://127.0.0.1:11434'
      - 'WEBUI_NAME=Ampere Llama Chat'
    restart: unless-stopped

volumes:
  ollama:
    name: ollama-vol
  open-webui:
    name: open-webui-vol
